### ISSUE TITLE
ImportError: No module named pdfminer.converter

### ISSUE THREAD

**Issue by baljeet** [skcript/cvscan#13]
This is the stacktrace:

Traceback (most recent call last):
  File "/usr/local/bin/cvscan", line 11, in <module>
    load_entry_point('cvscan==0.0.1', 'console_scripts', 'cvscan')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/cvscan-0.0.1-py2.7.egg/cvscan/__init__.py", line 8, in <module>
    import converter
  File "/usr/local/lib/python2.7/dist-packages/cvscan-0.0.1-py2.7.egg/cvscan/converter.py", line 13, in <module>
    from pdfminer.converter import TextConverter
ImportError: No module named pdfminer.converter

**Comment by lakshmanaram** [comment]
Has been resolved. Check issuing the command
`python setup.py install`

Thanks for pointing it out...:)
