### ISSUE TITLE
[Python 3.6] import converter ModuleNotFoundError: No module named 'converter'

### ISSUE THREAD

**Issue by Lubdhak** [skcript/cvscan#23]
```
lubi:cvscan-master lubi$ python setup.py install
running install
running bdist_egg
running egg_info
writing cvscan.egg-info/PKG-INFO
writing dependency_links to cvscan.egg-info/dependency_links.txt
writing entry points to cvscan.egg-info/entry_points.txt
writing requirements to cvscan.egg-info/requires.txt
writing top-level names to cvscan.egg-info/top_level.txt
reading manifest file 'cvscan.egg-info/SOURCES.txt'
writing manifest file 'cvscan.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.12-x86_64/egg
creating build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/__init__.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/annotations_parser.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/cli
copying build/lib/cvscan/cli/__init__.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/cli
copying build/lib/cvscan/cli/cli.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/cli
copying build/lib/cvscan/configurations.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/converter.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/address_processor.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/district-states -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/pincode-district-state -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/pincodes -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/states -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/extra
copying build/lib/cvscan/data/extra/extra -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/extra
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions
copying build/lib/cvscan/data/job_positions/positions -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions
copying build/lib/cvscan/data/job_positions/positions.xlsx -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions
copying build/lib/cvscan/data/job_positions/scraping_jobs.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/organizations
copying build/lib/cvscan/data/organizations/avoid_organizations -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/organizations
copying build/lib/cvscan/data/organizations/explicit_organizations -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/organizations
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/qualifications
copying build/lib/cvscan/data/qualifications/degree -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/qualifications
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/sample
copying build/lib/cvscan/data/sample/lakshmanaram.pdf -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/sample
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills
copying build/lib/cvscan/data/skills/scraping_skills.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills
copying build/lib/cvscan/data/skills/skills -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills
copying build/lib/cvscan/data/skills/skills.bak -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills
copying build/lib/cvscan/data_operations.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/details_parser.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/dirpath.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/language_parser.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/utilities.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/annotations_parser.py to annotations_parser.cpython-36.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/cvscan/annotations_parser.py", line 46
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/cli/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/cli/cli.py to cli.cpython-36.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/cvscan/cli/cli.py", line 83
    print "Something wnet wrong: " + Exception
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Something wnet wrong: " + Exception)?

byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/configurations.py to configurations.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/converter.py to converter.cpython-36.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/cvscan/converter.py", line 60
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address/address_processor.py to address_processor.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions/scraping_jobs.py to scraping_jobs.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills/scraping_skills.py to scraping_skills.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/data_operations.py to data_operations.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/details_parser.py to details_parser.cpython-36.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/cvscan/details_parser.py", line 34
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/dirpath.py to dirpath.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/language_parser.py to language_parser.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/utilities.py to utilities.cpython-36.pyc
creating build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/PKG-INFO -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/SOURCES.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/dependency_links.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/entry_points.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/requires.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/top_level.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
cvscan.__pycache__.dirpath.cpython-36: module references __file__
creating 'dist/cvscan-0.0.1-py3.6.egg' and adding 'build/bdist.macosx-10.12-x86_64/egg' to it
removing 'build/bdist.macosx-10.12-x86_64/egg' (and everything under it)
Processing cvscan-0.0.1-py3.6.egg
removing '/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg
Extracting cvscan-0.0.1-py3.6.egg to /usr/local/lib/python3.6/site-packages
  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/annotations_parser.py", line 46
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/converter.py", line 60
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/details_parser.py", line 34
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/cli/cli.py", line 83
    print "Something wnet wrong: " + Exception
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Something wnet wrong: " + Exception)?

cvscan 0.0.1 is already the active version in easy-install.pth
Installing cvscan script to /usr/local/bin

Installed /usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg
Processing dependencies for cvscan==0.0.1
Searching for numpy==1.11.3
Best match: numpy 1.11.3
Adding numpy 1.11.3 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for wheel==0.24.0
Best match: wheel 0.24.0
Adding wheel 0.24.0 to easy-install.pth file
Installing wheel script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages
Searching for pdfminer==20140328
Best match: pdfminer 20140328
Adding pdfminer 20140328 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for nltk==3.2.1
Best match: nltk 3.2.1
Adding nltk 3.2.1 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for click==6.7
Best match: click 6.7
Adding click 6.7 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Finished processing dependencies for cvscan==0.0.1
lubi:cvscan-master lubi$ 
lubi:cvscan-master lubi$ 
lubi:cvscan-master lubi$ 
lubi:cvscan-master lubi$ 
lubi:cvscan-master lubi$ cvscan parse
Traceback (most recent call last):
  File "/usr/local/bin/cvscan", line 11, in <module>
    load_entry_point('cvscan==0.0.1', 'console_scripts', 'cvscan')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/__init__.py", line 8, in <module>
    import converter
ModuleNotFoundError: No module named 'converter'
lubi:cvscan-master lubi$ cvscan parse
Traceback (most recent call last):
  File "/usr/local/bin/cvscan", line 11, in <module>
    load_entry_point('cvscan==0.0.1', 'console_scripts', 'cvscan')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/__init__.py", line 8, in <module>
    import converter
ModuleNotFoundError: No module named 'converter'
lubi:cvscan-master lubi$ ls
LICENSE                 cvscan                  dist
README.md               cvscan.egg-info         requirements.txt
build                   dev-requirements.txt    setup.py
lubi:cvscan-master lubi$ cvscan parse --cvscan/Lubdhak_Resume_v6.pdf
Traceback (most recent call last):
  File "/usr/local/bin/cvscan", line 11, in <module>
    load_entry_point('cvscan==0.0.1', 'console_scripts', 'cvscan')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
lubi:cvscan-master lubi$ ls
LICENSE                 cvscan                  dist
README.md               cvscan.egg-info         requirements.txt
build                   dev-requirements.txt    setup.py
lubi:cvscan-master lubi$ cd cvscan
lubi:cvscan lubi$ python setup.py install
/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory
lubi:cvscan lubi$ ls
__init__.py             converter.py            dirpath.py
annotations_parser.py   data                    language_parser.py
cli                     data_operations.py      utilities.py
configurations.py       details_parser.py
lubi:cvscan lubi$ cd ..
lubi:cvscan-master lubi$ ls
LICENSE                 cvscan                  requirements.txt
README.md               dev-requirements.txt    setup.py
lubi:cvscan-master lubi$ python setup.py install
running install
running bdist_egg
running egg_info
creating cvscan.egg-info
writing cvscan.egg-info/PKG-INFO
writing dependency_links to cvscan.egg-info/dependency_links.txt
writing entry points to cvscan.egg-info/entry_points.txt
writing requirements to cvscan.egg-info/requires.txt
writing top-level names to cvscan.egg-info/top_level.txt
writing manifest file 'cvscan.egg-info/SOURCES.txt'
reading manifest file 'cvscan.egg-info/SOURCES.txt'
writing manifest file 'cvscan.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.12-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/cvscan
copying cvscan/__init__.py -> build/lib/cvscan
copying cvscan/annotations_parser.py -> build/lib/cvscan
copying cvscan/configurations.py -> build/lib/cvscan
copying cvscan/converter.py -> build/lib/cvscan
copying cvscan/data_operations.py -> build/lib/cvscan
copying cvscan/details_parser.py -> build/lib/cvscan
copying cvscan/dirpath.py -> build/lib/cvscan
copying cvscan/language_parser.py -> build/lib/cvscan
copying cvscan/utilities.py -> build/lib/cvscan
creating build/lib/cvscan/cli
copying cvscan/cli/__init__.py -> build/lib/cvscan/cli
copying cvscan/cli/cli.py -> build/lib/cvscan/cli
creating build/lib/cvscan/data
creating build/lib/cvscan/data/address
copying cvscan/data/address/address_processor.py -> build/lib/cvscan/data/address
copying cvscan/data/address/district-states -> build/lib/cvscan/data/address
copying cvscan/data/address/pincode-district-state -> build/lib/cvscan/data/address
copying cvscan/data/address/pincodes -> build/lib/cvscan/data/address
copying cvscan/data/address/states -> build/lib/cvscan/data/address
creating build/lib/cvscan/data/extra
copying cvscan/data/extra/extra -> build/lib/cvscan/data/extra
creating build/lib/cvscan/data/job_positions
copying cvscan/data/job_positions/positions -> build/lib/cvscan/data/job_positions
copying cvscan/data/job_positions/positions.xlsx -> build/lib/cvscan/data/job_positions
copying cvscan/data/job_positions/scraping_jobs.py -> build/lib/cvscan/data/job_positions
creating build/lib/cvscan/data/organizations
copying cvscan/data/organizations/avoid_organizations -> build/lib/cvscan/data/organizations
copying cvscan/data/organizations/explicit_organizations -> build/lib/cvscan/data/organizations
creating build/lib/cvscan/data/qualifications
copying cvscan/data/qualifications/degree -> build/lib/cvscan/data/qualifications
creating build/lib/cvscan/data/sample
copying cvscan/data/sample/lakshmanaram.pdf -> build/lib/cvscan/data/sample
creating build/lib/cvscan/data/skills
copying cvscan/data/skills/scraping_skills.py -> build/lib/cvscan/data/skills
copying cvscan/data/skills/skills -> build/lib/cvscan/data/skills
copying cvscan/data/skills/skills.bak -> build/lib/cvscan/data/skills
creating build/bdist.macosx-10.12-x86_64
creating build/bdist.macosx-10.12-x86_64/egg
creating build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/__init__.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/annotations_parser.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/cli
copying build/lib/cvscan/cli/__init__.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/cli
copying build/lib/cvscan/cli/cli.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/cli
copying build/lib/cvscan/configurations.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/converter.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/address_processor.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/district-states -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/pincode-district-state -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/pincodes -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
copying build/lib/cvscan/data/address/states -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/extra
copying build/lib/cvscan/data/extra/extra -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/extra
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions
copying build/lib/cvscan/data/job_positions/positions -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions
copying build/lib/cvscan/data/job_positions/positions.xlsx -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions
copying build/lib/cvscan/data/job_positions/scraping_jobs.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/organizations
copying build/lib/cvscan/data/organizations/avoid_organizations -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/organizations
copying build/lib/cvscan/data/organizations/explicit_organizations -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/organizations
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/qualifications
copying build/lib/cvscan/data/qualifications/degree -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/qualifications
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/sample
copying build/lib/cvscan/data/sample/lakshmanaram.pdf -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/sample
creating build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills
copying build/lib/cvscan/data/skills/scraping_skills.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills
copying build/lib/cvscan/data/skills/skills -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills
copying build/lib/cvscan/data/skills/skills.bak -> build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills
copying build/lib/cvscan/data_operations.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/details_parser.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/dirpath.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/language_parser.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
copying build/lib/cvscan/utilities.py -> build/bdist.macosx-10.12-x86_64/egg/cvscan
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/annotations_parser.py to annotations_parser.cpython-36.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/cvscan/annotations_parser.py", line 46
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/cli/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/cli/cli.py to cli.cpython-36.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/cvscan/cli/cli.py", line 83
    print "Something wnet wrong: " + Exception
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Something wnet wrong: " + Exception)?

byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/configurations.py to configurations.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/converter.py to converter.cpython-36.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/cvscan/converter.py", line 60
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/data/address/address_processor.py to address_processor.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/data/job_positions/scraping_jobs.py to scraping_jobs.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/data/skills/scraping_skills.py to scraping_skills.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/data_operations.py to data_operations.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/details_parser.py to details_parser.cpython-36.pyc
  File "build/bdist.macosx-10.12-x86_64/egg/cvscan/details_parser.py", line 34
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/dirpath.py to dirpath.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/language_parser.py to language_parser.cpython-36.pyc
byte-compiling build/bdist.macosx-10.12-x86_64/egg/cvscan/utilities.py to utilities.cpython-36.pyc
creating build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/PKG-INFO -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/SOURCES.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/dependency_links.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/entry_points.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/requires.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
copying cvscan.egg-info/top_level.txt -> build/bdist.macosx-10.12-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
cvscan.__pycache__.dirpath.cpython-36: module references __file__
creating dist
creating 'dist/cvscan-0.0.1-py3.6.egg' and adding 'build/bdist.macosx-10.12-x86_64/egg' to it
removing 'build/bdist.macosx-10.12-x86_64/egg' (and everything under it)
Processing cvscan-0.0.1-py3.6.egg
removing '/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg' (and everything under it)
creating /usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg
Extracting cvscan-0.0.1-py3.6.egg to /usr/local/lib/python3.6/site-packages
  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/annotations_parser.py", line 46
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/converter.py", line 60
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/details_parser.py", line 34
    except Exception, exception_instance:
                    ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/cli/cli.py", line 83
    print "Something wnet wrong: " + Exception
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Something wnet wrong: " + Exception)?

cvscan 0.0.1 is already the active version in easy-install.pth
Installing cvscan script to /usr/local/bin

Installed /usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg
Processing dependencies for cvscan==0.0.1
Searching for numpy==1.11.3
Best match: numpy 1.11.3
Adding numpy 1.11.3 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for wheel==0.24.0
Best match: wheel 0.24.0
Adding wheel 0.24.0 to easy-install.pth file
Installing wheel script to /usr/local/bin

Using /usr/local/lib/python3.6/site-packages
Searching for pdfminer==20140328
Best match: pdfminer 20140328
Adding pdfminer 20140328 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for nltk==3.2.1
Best match: nltk 3.2.1
Adding nltk 3.2.1 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Searching for click==6.7
Best match: click 6.7
Adding click 6.7 to easy-install.pth file

Using /usr/local/lib/python3.6/site-packages
Finished processing dependencies for cvscan==0.0.1
lubi:cvscan-master lubi$ 
lubi:cvscan-master lubi$ cvscan parse --lubi lubi:cvscan-master lubi$ 
Traceback (most recent call last):
  File "/usr/local/bin/cvscan", line 11, in <module>
    load_entry_point('cvscan==0.0.1', 'console_scripts', 'cvscan')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/cvscan-0.0.1-py3.6.egg/cvscan/__init__.py", line 8, in <module>
    import converter
ModuleNotFoundError: No module named 'converter'
lubi:cvscan-master lubi$ 

```

**Comment by dharmajmrd** [comment]
I am also facing same issue.. Any update?

**Comment by Navdevl** [comment]
The package was initially designed to support Python 2.7. You can try porting it to Python 3.5 and above and raise a PR. It was tested and found to be working with 2.7. @dharmajmrd @Lubdhak :))
Else, I will try to port it to support python 3 sooner.

**Comment by kbrajwani** [comment]
first of thanks to share such a good code.
Here i converted this repo from python 2 to 3 i hope it will help you.

https://github.com/kbrajwani/cvscan3

**Comment by Lubdhak** [comment]
@kbrajwani : Kudos!
